DressSewingWebView/Controllers/MainController.cs
using DressSewingServiceDAL.BindingModels;
using DressSewingServiceDAL.Interfaces;
using DressSewingServiceDAL.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DressSewingWebView.Controllers
{
    public class MainController : Controller
    {
        private readonly IMainService _service;
        private readonly IDressService _dressService;
        private readonly IDesignerService _designerService;

        public MainController(IMainService service, IDressService dressService, IDesignerService designerService)
        {
            _service = service;
            _dressService = dressService;
            _designerService = designerService;
        }
        
        public ActionResult Index()
        {
            return View(_service.GetList());
        }

        public ActionResult Create()
        {
            var dresses = new SelectList(_dressService.GetList(), "Id", "DressName");
            var designers = new SelectList(_designerService.GetList(), "Id", "DesignerFIO");
            ViewBag.Dresses = dresses;
            ViewBag.Designers = designers;
            return View();
        }

        [HttpPost]
        public ActionResult CreatePost()
        {
            var designerId = int.Parse(Request["DesignerId"]);
            var dressId = int.Parse(Request["DressId"]);
            var count = int.Parse(Request["Count"]);
            var sum = CalcSum(dressId, count);

            _service.CreateRequest(new RequestBindingModel
            {
                DesignerId = designerId,
                DressId = dressId,
                Count = count,
                Sum = sum

            });
            return RedirectToAction("Index");
        }

        private Decimal CalcSum(int Id, int Count)
        {
            DressViewModel dress = _dressService.GetElement(Id);
            return Count * dress.Price;
        }

        public ActionResult SetStatus(int id, string status)
        {
            try
            {
                switch (status)
                {
                    case "Processing":
                        _service.TakeRequestInWork(new RequestBindingModel { Id = id });
                        break;
                    case "Ready":
                        _service.FinishRequest(new RequestBindingModel { Id = id });
                        break;
                    case "Paid":
                        _service.PayRequest(new RequestBindingModel { Id = id });
                        break;
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
            }


            return RedirectToAction("Index");
        }
    }
}

DressSewingWebView/Views/Main/Create.cshtml
@model DressSewingServiceDAL.BindingModels.RequestBindingModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("CreatePost", "Main", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RequestBindingModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DesignerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DesignerId", ViewBag.Designers as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DressId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DressId", ViewBag.Dresses as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DressSewingWebView/Views/Main/Index.cshtml
@model IEnumerable<DressSewingServiceDAL.ViewModels.RequestViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DesignerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DesignerFIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DressId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DressName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateImplement)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DesignerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DesignerFIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DressId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DressName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateImplement)
        </td>
        <td>
            @Html.ActionLink("Отдать на выполнение", "SetStatus", new { id = item.Id, status = "Processing" }) |
            @Html.ActionLink("Заказ готов", "SetStatus", new { id = item.Id, status = "Ready" }) |
            @Html.ActionLink("Заказ оплачен", "SetStatus", new { id = item.Id, status = "Paid" })
        </td>
    </tr>
}

</table>