DressSewingWebView/Controllers/StoresController.cs
using DressSewingServiceDAL.BindingModels;
using DressSewingServiceDAL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DressSewingWebView.Controllers
{
    public class StoresController : Controller
    {
        private readonly IStoreService _service;
        private readonly IMaterialService _matService;
        private readonly IMainService _mainService;

        public StoresController(IStoreService service, IMaterialService matService, IMainService mainService)
        {
            _service = service;
            _matService = matService;
            _mainService = mainService;
        }

        public ActionResult Index()
        {
            return View(_service.GetList());
        }

        public ActionResult Details(int id)
        {
            return View(_service.GetElement(id));
        }

        public ActionResult Delete(int id)
        {
            _service.DelElement(id);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePost()
        {
            _service.AddElement(new StoreBindingModel
            {
                StoreName = Request["StoreName"]
            });
            return RedirectToAction("Index");
        }

        public ActionResult AddMaterial()
        {
            var stores = new SelectList(_service.GetList(), "Id", "StoreName");
            ViewBag.Stores = stores;
            var materials = new SelectList(_matService.GetList(), "Id", "MaterialName");
            ViewBag.Materials = materials;
            return View();
        }

        [HttpPost]
        public ActionResult AddMaterialPost()
        {
            _mainService.PutMaterialInStore(new StoreMaterialBindingModel
            {
                MaterialId = int.Parse(Request["MaterialId"]),
                StoreId = int.Parse(Request["StoreId"]),
                Count = int.Parse(Request["Count"])
            });
            return RedirectToAction("Index");
        }
    }
}

DressSewingWebView/Views/Stores/AddMaterial.cshtml
@model DressSewingServiceDAL.BindingModels.StoreMaterialBindingModel

@{
    ViewBag.Title = "AddMaterial";
}

<h2>AddMaterial</h2>


@using (Html.BeginForm("AddMaterialPost", "Stores", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StoreMaterialBindingModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StoreId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StoreId", ViewBag.Stores as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaterialId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaterialId", ViewBag.Materials as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DressSewingWebView/Views/Stores/Create.cshtml
@model DressSewingServiceDAL.BindingModels.StoreBindingModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("CreatePost", "Stores", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StoreBindingModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StoreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StoreName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StoreName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DressSewingWebView/Views/Stores/Details.cshtml
@model DressSewingServiceDAL.ViewModels.StoreViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>StoreViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StoreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreName)
        </dd>

    </dl>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StoreMaterials[0].MaterialName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoreMaterials[0].Count)
            </th>
        </tr>

        @foreach (var item in Model.StoreMaterials)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaterialName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Count)
                </td>
                <td></td>
            </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DressSewingWebView/Views/Stores/Index.cshtml
@model IEnumerable<DressSewingServiceDAL.ViewModels.StoreViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StoreName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StoreName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>